type = "agent"

functions = ["all"]
models = ["all"]

[entrypoint]
prod = ".venv/bin/python3 -m src"
dev = ".venv/bin/uvicorn src.main:app --reload --port 1338 --host 0.0.0.0 --loop asyncio"

[[triggers]]
id = "http"
type = "http"

[triggers.configuration]
path = "/docbot"
authenticationType = "public"

[env]
INBOX_USERNAME = "$INBOX_USERNAME"
AGENTMAIL_API_KEY = "${secrets.AGENTMAIL_API_KEY}"
