apiVersion: blaxel.ai/v1alpha1
kind: IntegrationConnection
metadata:
  name: agentmail-integration
spec:
  integration: agentmail
  secret:
    agentmailApiKey: ${secrets.AGENTMAIL_API_KEY}
---
apiVersion: blaxel.ai/v1alpha1
kind: Function
metadata:
  displayName: agentmail
  name: agentmail
spec:
  integrationConnections:
    - agentmail-integration
  runtime:
    type: mcp
